name: Deploy Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          registry-url: 'https://npm.pkg.github.com'

      - name: Detect Modified Packages
        run: |
          echo "modified_packages=package-1 build-tools" >> $GITHUB_ENV

      - name: Install
        run: for package in ${{ env.modified_packages }}; do (cd "packages/$package" && npm install); done

      - name: Build 1
        run: for package in ${{ env.modified_packages }}; do (cd "packages/$package" && npm run build); done

      - name: Build 2 (temp fix)
        run: for package in ${{ env.modified_packages }}; do (cd "packages/$package" && npm run build); done

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: for package in ${{ env.modified_packages }}; do (cd "packages/$package/dist" && npm publish); done
